New files

diff --git a/addingUsers b/addingUsers
--- a/addingUsers
+++ b/addingUsers
@@ -3,70 +3,57 @@
 input="names.txt"
 declare -a userNameArr
 
-while IFS= read -r currentLine
+while IFS=$'\t' read -r -a currentLine
 do
-   lastname=""
+
+   lastName=""
    firstNameChar=""
    middleNameChar=""
-   numberTwo="2"
-   # Keep track of the index so we can know which part of the line we're on.
-   index=0;
-   for word in $currentLine
-   # Use a 'for' loop to iterate through every line individually
-   do
-	if [[ $index != 0 ]]
-	# Skip over the first couple letters (index 0) becayse we never have to use them.
-	then
-	    if [[ $index == 1 ]]
-	    # This is the index of the last name.
-	    then
-		# strips all the non-alphabetic chars from the lastname
-		lastName="${word//[^[:alpha:]]/}"
-	    fi	    
+   lengthOfCurrentLine=${#currentLine[@]}
 
-	    if ! [[ $word =~ [A-Z]{2,4} ]]
-	    # This is a regex expression. It checks to find the all-caps abbreviation for the person's major. (e.g. COM or MBA.) if we find it, then we know we're at the end of the line.
-	    then
-
-	    	if [[ $index == 2 ]]
-	    	# This is the index of the first name.
-	    	then
-			# Takes the first char of the firstname
-			firstNameChar=${word::1}
-	   
-	   	 elif [[ $index == 3 ]]
-	    	# This is the index of the middle initial
-	    	then
-			# Takest the first char of the middlename
-			middleNameChar=${word::1}
-	    	fi
+   if [[ $lengthOfCurrentLine -ge 3 ]]
+   then
+	lastName=${currentLine[1]}
+	lastName="${lastName//[^[:alpha:]]/}"
+   	if [[ $lengthOfCurrentLine -ge 4 ]]
+   	then
+	    firstNameChar=${currentLine[2]}
+            firstNameChar=${firstNameChar::1}
+	    if [[ $lengthOfCurrentLine == 5 ]]
+   	    then
+		middleNameChar=${currentLine[3]}
+        	middleNameChar=${middleNameChar::1}
 	    fi
 	fi
-	((index++))
-   done  
-
+   else
+        echo "We were unable to process information for "${currentLine[@]}
+        flag=true
+   fi
+   
    # Concatenate the string together to create the username & make it lowercase
-   username="$firstNameChar$middleNameChar$lastName"
-   username=$(echo $username | tr [:upper:] [:lower:])
-    #echo $username
+   if [[ flag != true ]]
+   then
+	echo $lastName
+	username="$firstNameChar$middleNameChar$lastName"
+   	username=$(echo $username | tr [:upper:] [:lower:])
 
-   # Check to see if there is a duplicate username
-   while [[ ${userNameArr[@]} =~ ${username} ]]
-   do
-	lastCharInUser=${username: -1}
-	if ! [[ $lastCharInUser =~ ^[0-9]+$ ]]
-	then
-	    username="$username$numberTwo"
-	else
-	    lastCharInUser=$(($lastCharInUser + 1))
-	    username="${username%?}$lastCharInUser"
-	fi
-   done
+        # Check to see if there is a duplicate username
+   	while [[ " ${userNameArr[@]} " =~ " ${username} " ]]
+   	do
+	    lastCharInUser=${username: -1}
+	    if ! [[ $lastCharInUser =~ ^[0-9]+$ ]]
+	    then
+		username="$username""2"
+	    else
+	        lastCharInUser=$(($lastCharInUser + 1))
+	    	username="${username%?}$lastCharInUser"
+	    fi
+  	done
 
-   userNameArr+=($username)
-   echo $username >> usernames.txt
-   #useradd $username
-
+   	userNameArr+=($username)
+  	echo $username >> usernames.txt
+   	#useradd $username
+    fi
 done < "names.txt"
 # echo "AND NOW, HERE IS THE ARRAY!"
 # echo ${userNameArr[*]}
